Revert "Only allow DispVM templates to have appmenus-dispvm feature"
A DispVM created out of DispVM template will have the 'appmenus-dispvm'
feature set: it will be copied when creating the DispVM by design.
This fixes:
    AttributeError: 'DispVM' object has no attribute 'template_for_dispvms'

This reverts commit 2766b71d84dc43b4c4aa8f2ea27bded17df4f05e.